---
version: "3.9"
networks:
  xapitools0: {}
volumes:
  xapitools_simulations: {}

services:
  mariadb:
    image: library/mariadb:10.7
    networks:
      - xapitools0
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: xapitools
      MARIADB_USER: xapi
      MARIADB_PASSWORD: toolkit
  datasim:
    # Image is built by CI of DATASIM "mirror"
    image: nexus.galaxion.de:5050/yetanalytics/datasim:latest
    entrypoint: bin/server.sh                                       # The default is to run DATASIM in CLI mode. We probably want to override that.
    networks:
      - xapitools0
    environment:
      credentials: foo:bar  # sic!
    ports:
      - "9090:9090"
  permission_control:
    image: busybox
    command: /bin/sh -c 'touch /data/.initialized && chown -R 1000:1000 /data'
    volumes:
      - xapitools_simulations:/data
  xapitools:
    depends_on:
      - mariadb
      - datasim
      - permission_control
    restart: on-failure
    # Image is built by CI of this project.
    image: nexus.galaxion.de:5050/de.tudresden.inf.verdatas/xapitools:latest
    networks:
      - xapitools0
    volumes:
      - xapitools_simulations:/data
    ports:
      - "8888:8080"                                                 # The service is mapped to port 8888 on localhost without TLS. Perhaps integrate Træfik?
    environment:
      XAPITOOLS_SEC_USERNAME: foo
      XAPITOOLS_SEC_PASSWORD: bar
      XAPITOOLS_SIM_BACKEND_BASE_URL: http://datasim:9090   # This is the Docker-relative base path.
      XAPITOOLS_SIM_BACKEND_USERNAME: foo
      XAPITOOLS_SIM_BACKEND_PASSWORD: bar
      XAPITOOLS_SIM_STORAGE_DIR: /data                              # This path also is Docker-relative. See volumes section.
      XAPITOOLS_DB_CONNECTION_STRING: mariadb://mariadb:3306/xapitools
      XAPITOOLS_DB_CONNECTION_USER: xapi
      XAPITOOLS_DB_CONNECTION_PASSWORD: toolkit
      TZ: Europe/Berlin
